### ISSUE TITLE
The truth value of a Series is ambiguous in equivalent rectangular index

### ISSUE THREAD

**Issue by Arch4060** [pysal/momepy#528] opened 2024-01-03 01:21 UTC
### Describe the problem

```
Buildings_gdf['eri'] = momepy.EquivalentRectangularIndex(Buildings_gdf).series


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[~\AppData\Local\Temp\ipykernel_21260\3185557984.py](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/glass/Documents/0_PRIVAT/DISSERTATION/SCRIPTS/~/AppData/Local/Temp/ipykernel_21260/3185557984.py) in <cell line: 4>()
      2 print(Buildings_gdf[(Buildings_gdf.is_empty == True)])
      3 print(Buildings_gdf.geom_type.value_counts())
----> 4 Buildings_gdf['eri'] = momepy.EquivalentRectangularIndex(Buildings_gdf).series
      5 #Buildings_gdf['elongation'] = momepy.Elongation(Buildings_gdf).series
      6 

[c:\Users\glass\anaconda3\envs\basic_update\lib\site-packages\momepy\shape.py](file:///C:/Users/glass/anaconda3/envs/basic_update/lib/site-packages/momepy/shape.py) in __init__(self, gdf, areas, perimeters)
   1052 
   1053         self.areas = areas
-> 1054         bbox = shapely.minimum_rotated_rectangle(gdf.geometry)
   1055         res = np.sqrt(areas / bbox.area) * (bbox.length / perimeters)
   1056 

[c:\Users\glass\anaconda3\envs\basic_update\lib\site-packages\shapely\constructive.py](file:///C:/Users/glass/anaconda3/envs/basic_update/lib/site-packages/shapely/constructive.py) in oriented_envelope(geometry, **kwargs)
   1032     else:
   1033         f = _oriented_envelope_geos
-> 1034     return f(geometry, **kwargs)
   1035 
   1036 

[c:\Users\glass\anaconda3\envs\basic_update\lib\site-packages\shapely\algorithms\_oriented_envelope.py](file:///C:/Users/glass/anaconda3/envs/basic_update/lib/site-packages/shapely/algorithms/_oriented_envelope.py) in _oriented_envelope_min_area(geometry, **kwargs)
     20     if not hasattr(geometry, "geom_type"):
     21         return np.array([_oriented_envelope_min_area(g) for g in geometry])
---> 22     if geometry.is_empty:
     23         return shapely.from_wkt("POLYGON EMPTY")
     24 

[c:\Users\glass\anaconda3\envs\basic_update\lib\site-packages\pandas\core\generic.py](file:///C:/Users/glass/anaconda3/envs/basic_update/lib/site-packages/pandas/core/generic.py) in __nonzero__(self)
   1525     @final
   1526     def __nonzero__(self):
-> 1527         raise ValueError(
   1528             f"The truth value of a {type(self).__name__} is ambiguous. "
   1529             "Use a.empty, a.bool(), a.item(), a.any() or a.all()."

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

### Steps to reproduce

```
print(Buildings_gdf['geometry'])
print(Buildings_gdf[(Buildings_gdf.is_empty == True)])
print(Buildings_gdf.geom_type.value_counts())

0      POLYGON ((68922.930 351142.920, 68920.840 3511...
1      POLYGON ((68219.090 352207.080, 68215.270 3522...
2      POLYGON ((68227.832 352203.820, 68227.793 3521...
3      POLYGON ((68052.600 350526.860, 68038.740 3505...
4      POLYGON ((68717.018 352147.076, 68703.141 3521...
                             ...                        
853    POLYGON ((67702.588 350427.867, 67692.834 3504...
854    POLYGON ((68052.933 350575.870, 68049.441 3505...
855    POLYGON ((68020.540 352384.088, 68013.430 3523...
856    POLYGON ((67918.920 350965.390, 67919.250 3509...
857    POLYGON ((69125.200 350819.160, 69124.750 3508...
Name: geometry, Length: 858, dtype: geometry
Empty GeoDataFrame
Columns: [OBJECTID_1, BAUWERKSFUNKTION, AGWR_OBJEKTNUMMER, AGWR_TYP, HOEHE_BODEN_MIN, HOEHE_BODEN_MEDIAN, HOEHE_BODEN_MAX, HOEHE_OBJEKT_MEDIAN, HOEHE_OBJEKT_MAX, GLOBALID, F_CODE_P, F_CODE_P_NAME_ART, Area, Perimeter, CircumcircleRadius, AreaRectangle, AreaRectangleRatio, Volume, geometry, uID, LINK_ID, NAME1, NAME2, FROM_NODE, TO_NODE, SPEEDCAR_T, SPEEDCAR_B, VMAX_CAR_T, VMAX_CAR_B, ACCESS_TOW, ACCESS_BKW, LENGTH, FRC, LANES_TOW, LANES_BKW, FORMOFWAY, MAXHEIGHT, MAXWIDTH, MAXPRESS, ABUTTERCAR, URBAN, WIDTH, TOLL, BAUSTATUS, SUBNET_ID, ONEWAY_CAR, ONEWAY_BK, ONEWAY_BUS, EDGE_ID, EDGECAT, REGCODE, SUSTAINER, DBCON, SDE_ID, Shape_Leng, nID, area]
Index: []

[0 rows x 57 columns]
Polygon    858
dtype: int64
```

### Versions of your packages

```
print(momepy.__version__)
print(gpd.__version__)
print(libpysal.__version__)
import platform
print(platform.python_version())
```
```
0.6.0
0.14.1
4.8.1
3.9.13
```

### Your operating system

windows 

### Additional context

This is no OSM data set

**Comment by martinfleis** [comment] 2024-01-03 09:01
Hi @Arch4060,

thanks for the report. This is a known issue caused by a bug in shapely - https://github.com/shapely/shapely/issues/1929. You either need to ensure that you have GEOS 3.12 (ideal solution), which what you will get if you install latest versions using conda or mamba, or downgrade shapely to 2.0.1.

I will close this as it is nothing we can fix or our side. I suppose that it will be fixed in shapely 2.0.3 but updating GEOS is the best option anyway.

**Closed by martinfleis** 2024-01-03 09:01 UTC
Labels: bug
